name: 插件源自动化

on:
  push:
    branches:
      - main  # 当推送到 main 分支时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false  # 禁用子模块检查

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: 配置packages
        run: |
          sudo rm -f Packages Packages.bz2 Packages.gz
          sudo dpkg-scanpackages --multiversion debs >> Packages
          cat Packages | gzip > Packages.gz
          cat Packages | bzip2 > Packages.bz2

      - name: 设置Git配置
        run: |
          git config --global user.name 'wyxdlz54188'
          git config --global user.email 'lizi54188@outlook.com'

      - name: 上传GitHub pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ls -a
          git add .
          git commit -m "上传debs"
          git remote remove origin
          git remote add origin https://${{ secrets.GH_TOKEN }}@github.com/wyxdlz54188/repo.git
          git push origin HEAD:gh-pages -f

